### ISSUE TITLE
change our works scroll

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#10]
- [x] make 3 column, user can scroll horizontally
- [x] black background
![image](https://user-images.githubusercontent.com/30463117/226235210-5a524b4a-9de9-4e45-965d-c228daa35e3c.png)

similar to below
![image](https://user-images.githubusercontent.com/30463117/226235345-d0a90f1e-bc65-4ae1-89a3-6a7d1030b4ea.png)

reference:
https://theministryoftalent.com/

**Comment by norizwana** [comment]
![Screenshot 2023-03-22 100449](https://user-images.githubusercontent.com/124539751/226783516-6baff0c3-17d3-4ccd-881e-8b0a9a5d34cb.png)

**Comment by rosclaritha** [comment]
adjust padding, remove above our works
![image](https://user-images.githubusercontent.com/30463117/226786105-421bebed-fbe3-410b-99a1-530b8f12db44.png)

**Comment by norizwana** [comment]
![Screenshot 2023-03-24 100141](https://user-images.githubusercontent.com/124539751/227405324-618cd365-92c4-44b7-aff6-23f544d00cbf.png)
