### ISSUE TITLE
modify portfolio ui to fit with theme

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#11]
- [x] change menu
- [x] change footer
- [x] move description to below image

![image](https://user-images.githubusercontent.com/30463117/226237921-4e7f2d74-3605-4d3b-84fc-7ca8f20c396c.png)

**Comment by norizwana** [comment]
![Screenshot 2023-03-21 131942](https://user-images.githubusercontent.com/124539751/226525003-73cadaa5-90af-4b8b-a799-f1c818746898.png)

![Screenshot 2023-03-21 132140](https://user-images.githubusercontent.com/124539751/226525042-45d364aa-d1dd-4374-a502-bea3d53f6d1d.png)
