### ISSUE TITLE
change area of focus

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#12]
change image, content & styling to fit with theme

![image](https://user-images.githubusercontent.com/30463117/226238247-98efab2f-a93c-4563-9252-2ea740f512ad.png)

**Comment by norizwana** [comment]
![Screenshot 2023-03-21 145731](https://user-images.githubusercontent.com/124539751/226537011-d0d62caa-b5de-4258-b12a-6094db78627f.png)
