### ISSUE TITLE
change why we do styling

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#13]
change to fit with theme
![image](https://user-images.githubusercontent.com/30463117/226238418-8fe08021-7bea-45b5-870c-c3c5c3caf29a.png)

**Comment by norizwana** [comment]
![Screenshot 2023-03-21 112447](https://user-images.githubusercontent.com/124539751/226510936-980302cd-d305-453f-b994-90669cd9d6b3.png)

**Comment by rosclaritha** [comment]
change design & adjust padding
![image](https://user-images.githubusercontent.com/30463117/226785852-e27e22f1-a759-4d7e-b17a-32e4a9ac1ef5.png)

**Comment by norizwana** [comment]
![Screenshot 2023-03-27 105242](https://user-images.githubusercontent.com/124539751/227829235-8ecaef03-95fd-44fa-96c1-1890e31cf74a.png)

On Hover:-
![Screenshot 2023-03-27 105302](https://user-images.githubusercontent.com/124539751/227829239-8a50c507-8321-4342-8db7-72554495f6d6.png)
