### ISSUE TITLE
fix mobile view

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#14]

**Comment by norizwana** [comment]
![Screenshot 2023-03-28 110751](https://user-images.githubusercontent.com/124539751/228117846-454873ac-1466-4d95-891f-e45622583a87.png)
![Screenshot 2023-03-28 110811](https://user-images.githubusercontent.com/124539751/228117852-605a569c-cd54-4ca1-9f28-8582fb5d4d68.png)
![Screenshot 2023-03-28 110837](https://user-images.githubusercontent.com/124539751/228117855-71df0dd7-f8ac-4304-a192-e569c903c1d8.png)
![Screenshot 2023-03-28 110900](https://user-images.githubusercontent.com/124539751/228117858-daa459f2-d8bc-421e-8b3f-804ab7c8cb9f.png)
![Screenshot 2023-03-28 110908](https://user-images.githubusercontent.com/124539751/228117865-29f0cdc9-d8e4-4d6a-af2d-e1107d01bae5.png)
![Screenshot 2023-03-28 110920](https://user-images.githubusercontent.com/124539751/228117870-222a526c-e728-4b8d-9167-6507bfea0811.png)
![Screenshot 2023-03-28 110932](https://user-images.githubusercontent.com/124539751/228117876-c884d06e-002e-463f-916a-86f6aa2d0183.png)
