### ISSUE TITLE
update footer & contact us

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#15]
change styling to fit with theme & content
![image](https://user-images.githubusercontent.com/30463117/226240678-65978116-324c-4597-b9d4-88eed6c6b3f4.png)

follow:
![image](https://user-images.githubusercontent.com/30463117/226240583-d9f2bf4e-9705-480d-8d46-8b2dd81a5339.png)

**Comment by norizwana** [comment]
![Screenshot 2023-03-24 094756](https://user-images.githubusercontent.com/124539751/227403665-32fd1736-8725-4571-8e2c-3fcaf0408f78.png)
