### ISSUE TITLE
hide our works & our stories section

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#34]
just hide, do not delete
![image](https://user-images.githubusercontent.com/30463117/229444152-f405d5f3-2bc1-4bc5-80c3-aa59fe519403.png)
![image](https://user-images.githubusercontent.com/30463117/229445155-0f8329ab-bc52-4e65-aefc-9f75a78202ad.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (526)](https://user-images.githubusercontent.com/74038076/229666855-e8eaebbc-1a61-497c-b16d-fe392ed59df7.png) both sections came after service and before let's chat (already hide)
