### ISSUE TITLE
update website content

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#35]
[Content for Website - .pdf](https://github.com/phisoft/buzzybeepr-web/files/11135951/Content.for.Website.-.pdf)

**Comment by NadhirahIzzati** [comment]
![Screenshot (532)](https://user-images.githubusercontent.com/74038076/229726402-ea9c02b3-22e1-4bc4-adc3-1300cb8fec28.png)
![Screenshot (533)](https://user-images.githubusercontent.com/74038076/229726416-ed0af335-0512-463a-ac63-ec579a961c7b.png)
![Screenshot (534)](https://user-images.githubusercontent.com/74038076/229726422-063b9c1c-0b46-4c55-b43b-f34f0ec0d484.png)
![Screenshot (535)](https://user-images.githubusercontent.com/74038076/229726425-874278fa-472c-41c4-a9cd-3936cdc670fc.png)
![Screenshot (531)](https://user-images.githubusercontent.com/74038076/229726430-b7f4c8f9-cd4f-4f33-a1b1-79995663d421.png)
