### ISSUE TITLE
update contact us section

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#36]
![image](https://user-images.githubusercontent.com/30463117/229446336-239ed323-805f-4d9a-9e80-645e3448cf2e.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (525)](https://user-images.githubusercontent.com/74038076/229667031-d0c42bc2-b1e6-404a-94c2-cf577e4fcc89.png)
