### ISSUE TITLE
adjust why we do section for mobile view

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#37]
align all items center.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/30463117/229446818-828eedb0-869d-4613-9759-3da1ad6232a2.png">

similar to below:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/30463117/229451629-d4600db5-3aa9-466c-b1e0-d8d7f283e5f5.png">

**Comment by NadhirahIzzati** [comment]
![Uploading 229692661...]![image](https://user-images.githubusercontent.com/74038076/229692675-9defd6fe-b46c-43ed-9810-c5e19aca9c7d.png)

**Comment by NadhirahIzzati** [comment]
![image](https://user-images.githubusercontent.com/74038076/229692811-f49d3419-fca6-4617-9e83-aaa97ee11837.png)

![image](https://user-images.githubusercontent.com/74038076/229692881-de9a03db-d4a8-451d-8573-e7b2b743af61.png)
