### ISSUE TITLE
change header content

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#45]
Title: Growing Your Brand: PR Services for Hospitality and Tourism

Caption:
We are a Public Relations firm that focuses on managing the reputation, image &
communication of hospitality & tourism - related organizations such as hotels, restaurants,
resorts and tourist destinations.
Home to a quirky creative bunch, Buzzy Bee ensures your business is our business. Our main
goal is to create and maintain a positive image and reputation of the organization, attract and
retain customers, and enhance their experience. This is achieved by using various
communication strategies and tactics, such as media relations, event planning, crisis
management, influencer marketing, social media, and content creation.
We work closely with your management and marketing team in executing effective
communication to get your brand to where it needs to be. We work tirelessly to break the barrier
of traditional media and digital to convey your story the best way we know how. Through
monitoring and analyzing media coverage, customer feedback and industry trends to identify
potential opportunities and challenges that may impact your business as a whole.
Hospitality PR is a vital component of the hospitality industry, as it helps organizations build and
maintain a strong brand reputation, connect with customers, and drive revenue.

![image](https://user-images.githubusercontent.com/30463117/230003503-20783127-aad7-450a-bfb9-5b877d20a613.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (538)](https://user-images.githubusercontent.com/74038076/230012626-8e048391-e63c-4b04-8b1c-465faebaf0ea.png)
