### ISSUE TITLE
update services box size

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#60]
- [x] ensure that box size for `brand activation` & `event planning` remains the same for default state & on hovered.
e.g: box size for `influencer & collaboration outreach` & `media relations` are the same for default & on hover.

default state:
![image](https://github.com/phisoft/buzzybeepr-web/assets/30463117/783658e7-7265-4d79-9f91-5523a5bb1fb9)

on hovered:
1. `brand activation` -> on hovered the box size became smaller.
<img width="1377" alt="image" src="https://github.com/phisoft/buzzybeepr-web/assets/30463117/43112f40-df0e-404f-82aa-33eda1313fa6">

2. `event planning` -> on hovered the box size is bigger, ensure that the box size for both the brand activation & event planning size remain the same.
<img width="1443" alt="image" src="https://github.com/phisoft/buzzybeepr-web/assets/30463117/e4347467-3501-42c7-8ae5-e9b6e7b2bbb1">

**Comment by ChrsHnsn** [comment]
![Screenshot (899)](https://github.com/phisoft/buzzybeepr-web/assets/97533037/d977652e-9744-4ce0-9ad9-85433f8d5efd)
![Screenshot (898)](https://github.com/phisoft/buzzybeepr-web/assets/97533037/97f72d63-06fa-42bc-8eb4-57b86d01af46)
![Screenshot (897)](https://github.com/phisoft/buzzybeepr-web/assets/97533037/5cb09194-781d-4c92-a5dd-4994aa72b6f5)
![Screenshot (900)](https://github.com/phisoft/buzzybeepr-web/assets/97533037/21e170e0-4983-4745-acfd-903a36cf383e)
