### ISSUE TITLE
align img vertically centre with the right text

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#65]
<img width="1550" alt="image" src="https://github.com/phisoft/buzzybeepr-web/assets/30463117/00e9fd5a-94e8-42a8-8251-2f3d56e13eb8">

**Comment by ChrsHnsn** [comment]
![Screenshot (912)](https://github.com/phisoft/buzzybeepr-web/assets/97533037/f8c2a233-c017-41b7-8451-b3d50fc34431)

![Uploading Screenshot (911).png…]()
