### ISSUE TITLE
add top padding to description

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#66]
img and description too close. add padding in between.
![image](https://github.com/phisoft/buzzybeepr-web/assets/30463117/2506e9e6-8279-4a07-b992-005e593e0252)

**Comment by ChrsHnsn** [comment]
![Screenshot (914)](https://github.com/phisoft/buzzybeepr-web/assets/97533037/b3e9b284-783f-44b5-bc7e-62c3a79f4bf2)

**Comment by ChrsHnsn** [comment]
![Screen Shot 2023-06-13 at 14 53 36](https://github.com/phisoft/buzzybeepr-web/assets/97533037/9fab1dd8-945b-4686-b98c-c3cf15019225)
