### ISSUE TITLE
design case study list page

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#75]
bila pg sini `Case Study` menu:
<img width="432" alt="image" src="https://github.com/phisoft/buzzybeepr-web/assets/30463117/e73ac5c2-ace1-402f-b72b-22275505e270">

Redirect pg page bawah (need to be design):
![image](https://github.com/phisoft/buzzybeepr-web/assets/30463117/3372d840-7f06-4d72-a731-7eca706ef0f5)

When click on one the the list, redirect to case study:
![image](https://github.com/phisoft/buzzybeepr-web/assets/30463117/66c1e4c2-6c74-4a36-a04a-e823a8c8fa5e)

**Comment by ChrsHnsn** [comment]
![Screenshot (928)](https://github.com/phisoft/buzzybeepr-web/assets/97533037/0325b1ef-533d-47d9-bbd1-14020ec612fd)

![Screen Shot 2023-06-15 at 17 07 58-fullpage](https://github.com/phisoft/buzzybeepr-web/assets/97533037/42c6115e-643f-4405-a9a8-e8d0ed4cd7dc)
