### ISSUE TITLE
update website design

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/buzzybeepr-web#98]
![image](https://github.com/user-attachments/assets/afd0dc34-2861-4507-a00f-d2b53f7e319b)

for font, use the images:
[webdesignelements(1) 2.zip](https://github.com/user-attachments/files/17725132/webdesignelements.1.2.zip)

**Comment by tenzou92** [comment]
![image](https://github.com/user-attachments/assets/7b25e7e7-5086-4d03-934a-330da1038779)

**Comment by tenzou92** [comment]
![image](https://github.com/user-attachments/assets/3a8ceaa0-dc2c-49e3-ab56-fff1c370a9a6)

**Comment by tenzou92** [comment]
![image](https://github.com/user-attachments/assets/b0fc0f59-ebb4-47af-8037-47da153c9d1c)
